---
- name: Build Process on Ansible Slave
  hosts: "{{ target_ip }}"
  become: true
  tasks:
    - name: Install dependencies 
      apt:
        name:
          - openjdk-11-jdk
          - maven
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Clone the repository
      git:
        repo: "https://github.com/Charanraj2498/hello-world-war.git"
        dest: "/home/ubuntu/build"
        version: "master"

    - name: Build the project with Maven
      command: mvn clean package
      args:
        chdir: "/home/ubuntu/build"
