---
- name: Configure Build Node
  hosts: build_nodes  
  become: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - openjdk-11-jdk  
          - curl
        state: present

    - name: Create Jenkins user
      user:
        name: jenkins
        state: present
        home: /home/jenkins
        shell: /bin/bash

    - name: Set permissions for Jenkins home directory
      file:
        path: /home/jenkins
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
