---
- name: Build Process on Ansible Slave
  hosts: "{{ target_ip }}"
  become: true
  tasks:
    
    - name: Install required build tools
      apt:
        name: ["git", "maven", "openjdk-17-jdk"]
        state: present
        Update_cache: yes

    - name: Clone the repository
      git:
        repo: "https://github.com/Charanraj2498/hello-world-war.git"
        dest: "/home/ubuntu/build"
        version: "master"

    - name: Build the project with Maven
      command: mvn clean package
      args:
        chdir: "/home/ubuntu/build"
